
import React, {useState , useEffect} from "react"

let data=['Albania',
'Algeria',
'Andorra',
'Angola',
'Antigua and Barbuda',
'Argentina',
'Armenia',
'Australia',
'Austria',
'Austrian Empire*',
'Azerbaijan',
'B',
'Baden*',
'Bahamas, The',
'Bahrain',
'Bangladesh',
'Barbados',
'Bavaria*',
'Belarus',
'Belgium',
'Belize',
'Benin (Dahomey)',
'Bolivia',
'Bosnia and Herzegovina',
'Botswana',
'Brazil',
'Brunei',
'Brunswick and Lüneburg',
'Bulgaria',
'Burkina Faso (Upper Volta)',
'Burma',
'Burundi',
'C',
'Cabo Verde',
'Cambodia',
'Cameroon',
'Canada',
'Cayman Islands, The',
'Central African Republic',
'Central American Federation*',
'Chad',
'Chile',
'China',
'Colombia',
'Comoros',
'Congo Free State, The*',
'Costa Rica',
'Cote dIvoire (Ivory Coast)',
'Croatia',
'Cuba',
'Cyprus',
'Czechia',
'Czechoslovakia',
'D',
'Democratic Republic of the Congo',
'Denmark',
'Djibouti',
'Dominica',
'Dominican Republic',
'Duchy of Parma, The*',
'E',
'East Germany (German Democratic Republic)*',
'Ecuador',
'Egypt',
'El Salvador',
'Equatorial Guinea',
'Eritrea',
'Estonia',
'Eswatini',
'Ethiopia',
'F',
'Federal Government of Germany (1848-49)*',
'Fiji',
'Finland',
'France',
'G',
'Gabon',
'Gambia, The',
'Georgia',
'Germany',
'Ghana',
'Grand Duchy of Tuscany, The*',
'Greece',
'Grenada',
'Guatemala',
'Guinea',
'Guinea-Bissau',
'Guyana',
'H',
'Haiti',
'Hanover*',
'Hanseatic Republics*',
'Hawaii*',
'Hesse*',
'Holy See',
'Honduras',
'Hungary',
'I',
'Iceland',
'India',
'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'J',
  'Jamaica',
  'Japan',
  'Jordan',
  'K',
  'Kazakhstan',
  'Kenya',
  'Kingdom of Serbia/Yugoslavia*',
  'Kiribati',
  'Korea',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'L',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Lew Chew (Loochoo)*',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'M',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mecklenburg-Schwerin*',
  'Mecklenburg-Strelitz*',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'N',
  'Namibia',
  'Nassau*',
  'Nauru',
  'Nepal',
  'Netherlands, The',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North German Confederation*',
  'North German Union*',
  'North Macedonia',
  'Norway',
  'O',
  'Oldenburg*',
  'Oman',
  'Orange Free State*',
  'P',
  'Pakistan',
  'Palau',
  'Panama',
  'Papal States*',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Piedmont-Sardinia*',
  'Poland',
  'Portugal',
  'Q',
  'Qatar',
  'R',
  'Republic of Genoa*',
  'Republic of Korea (South Korea)',
  'Republic of the Congo',
  'Romania',
  'Russia',
  'Rwanda',
  'S',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Schaumburg-Lippe*',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands, The',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'T',
  'Tajikistan',
  'Tanzania',
  'Texas*',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Two Sicilies*',
  'U',
  'Uganda',
  'Ukraine',
  'Union of Soviet Socialist Republics*',
  'United Arab Emirates, The',
  'United Kingdom, The',
  'Uruguay',
  'Uzbekistan',
  'V',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'W',
  'Württemberg*',
  'Y',
  'Yemen',
  'Z',
  'Zambia',
  'Zimbabwe'

]
const monthNames = ["January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"
];



const LiveSearch =()=>{
 
    const d = new Date();
    const m=d.getMonth();
    let [search , setSearch]=useState("");
    let [filterdata, setFilterdata]=useState(data);

    useEffect(
        ()=>{
            setFilterdata(data.filter((value)=>value.includes(search)));
        }
    )


    return (
        <div className="container">
            <h1> Welcome </h1>
            <h2>This is Mr Intikhab Islam</h2>
            <h3>Current Month : {monthNames[m]}</h3>
            <input type="text " id="search-item" placeholder="Search your country name here" value={search} onChange={(e)=>setSearch(e.target.value)}/>
            {
            filterdata.map((value)=>(
              <p>{value}</p>
            ))
         }
        </div>
        
    )
   
}



export default LiveSearch;